name: VYB
options:
  bundleIdPrefix: com.vyb
  deploymentTarget:
    iOS: "17.0"

targets:
  VYB:
    type: application
    platform: iOS
    sources:
      - path: VYB
        excludes:
          - "Services/VariationProcessor.swift"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: VYB
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.vyb.VYB
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies:
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework

  VYBTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - VYBTests
    settings:
      base:
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: vyb.VYBTests
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: VYB

  VYBUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - VYBUITests
    settings:
      base:
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: vyb.VYBUITests
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: VYB